/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SeguroMedico } from "./SeguroMedico";
export * as factories from "./factories";
export { SeguroMedico__factory } from "./factories/SeguroMedico__factory";
